apiVersion: databases.digitalocean.com/devops-db
kind: DatabaseClusterReference
metadata:
  name: devops-db

env:
  - name: MYSQL_HOST
    value: ${{ secrets.HOST_DB }}  # Vul de host in met de geheime waarde
  - name: MYSQL_PORT
    value: "25060"  # Vul de poort in
  - name: MYSQL_DATABASE
    value: "p2000"  # Vul de database in
  - name: MYSQL_USER
    value: "doadmin"  # Vul de gebruikersnaam in
  - name: MYSQL_PASSWORD
    value: ${{ secrets.DB_PASSWORD }} 

