apiVersion: databases.digitalocean.com/v1alpha1
kind: DatabaseClusterReference
metadata:
  name: p2000-db

env:
  - name: MYSQL_HOST
    valueFrom:
      configMapKeyRef:
        name: guestbook-db-private-connection
        key: ${{ secrets.HOST_DB }}  # De hostnaam van de database, komt uit de ConfigMap
  - name: MYSQL_PORT
    valueFrom:
      configMapKeyRef:
        name: guestbook-db-private-connection
        key: 25060  # De poort van de database, komt uit de ConfigMap
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: guestbook-db-private-connection
        key: p2000 # De naam van de database, komt uit de ConfigMap
  - name: MYSQL_USER
    valueFrom:
      secretKeyRef:
        name: guestbook-db-user-credentials
        key: doadmin  # De gebruikersnaam voor de database, komt uit de Secret
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: guestbook-db-user-credentials
        key: ${{ secrets.DB_PASSWORD }}  # Het wachtwoord voor de database, komt uit de Secret

