apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
  labels:
    app: python-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deploy
  template:
    metadata:
      labels:
        app: python-deploy
    spec:
      containers:
      - name: api
        image: placeholder_image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
        env:
        - name: MYSQL_USER
          value: "doadmin"
        - name: MYSQL_HOST
          value: "placeholder_host"
        - name: MYSQL_PORT
          value: "25060"
        - name: MYSQL_DB
          value: "p2000_rapportage"
        - name: MYSQL_PASSWORD
          value: "placeholder_passwd"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-deploy
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60


  


