apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
  labels:
    app: python-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deploy
  template:
    metadata:
      labels:
        app: python-deploy
    spec:
      containers:
      - name: python-deploy
        image: registry.digitalocean.com/project-devops/mathijs2002/devops:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_USER
          value: "doadmin"
        - name: MYSQL_HOST
          value: ${{ secrets.HOST_DB }}
        - name: MYSQL_PORT
          value: "25060"
        - name: MYSQL_DATABASE
          value: "p2000"
        - name: MYSQL_PASSWORD
          value: ${{ secrets.DB_PASSWORD }}


      


