apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: LoadBalancer
  selector:
    app: python-deploy
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080