name: cicd

on:
  push:
    branches:
      - main
      - mathijs-feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker HubS
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops:latest

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout files
        uses: actions/checkout@v2
      -
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      -
        name: Login to DigitalOcean Container Registry
        run: doctl registry login
      -
        name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/devops:latest
      -
        name: Docker tag
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/devops:latest registry.digitalocean.com/project-devops/mathijs2002/devops:latest
      -
        name: Push Docker image to DigitalOcean
        run: docker push registry.digitalocean.com/project-devops/mathijs2002/devops:latest
      - 
        name: Remove old images from Container Registry
        run: doctl registry garbage-collection start --include-untagged-manifests --force project-devops


  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      -
        name: Checkout files
        uses: actions/checkout@v2
      -
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      -
        name: Login to DigitalOcean Container Registry
        run: doctl registry login
      - 
        name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 python-api
      -
        name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f ${GITHUB_WORKSPACE}/config/deployment.yaml
      -
        name: Verify deployment
        run: kubectl rollout status deployment/python-deploy

    


      
    
        



    


     

    

    

          
