name: cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops:latest

  push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout files
        uses: actions/checkout@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      -
        name: Login to DigitalOcean Container Registry
        run: doctl registry login
      -
        name: Docker tag
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/devops:latest registry.digitalocean.com/project-devops/mathijs2002/devops:latest
      -
        name: Push Docker image to DigitalOcean
        run: docker push registry.digitalocean.com/project-devops/mathijs2002/devops:latest

        



    


     

    

    

          
