name: cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops:$(echo $GITHUB_SHA | head -c7) 


    
  push:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout files
        uses: actions/checkout@v2
      
      -
        name: get tag name
        uses: olegtarasov/get-tag@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      -
        name: login
        run: doctl registry login
      -
     
        name: push docker image digitalocean
        run: docker push docker push ${{ secrets.DOCKER_USERNAME }}/python-example:$(echo $GITHUB_SHA | head -c7)



    


     

    

    

          
