name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout files
        uses: actions/checkout@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          epository: mathijs2002/devops:latest
          tag_with_ref: true
          tag_with_sha: true

  push:
    runs-on: ubuntu-latest
    steps:
      -
       name: checkout files
       uses: actions/checkout@v2
      
      -
        name: get tag name
        uses: olegtarasov/get-tag@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      -
        name: login
        uses: doctl registry login
      -
        name: tag docker image digitalocean
        uses: docker tag mathijs2002/devops registry.digitalocean.com/project-devops/mathijs2002/devops
      -
        name: push docker image digitalocean
        uses: docker push registry.digitalocean.com/project-devops/mathijs2002/devops


    


     

    

    

          
